version: "3.9"
services:
  api:
    build: .
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: npm run dev
    ports:
      - ${APP_PORT}:80
    env_file:
      - .env
    networks:
      - api_net
    depends_on:
      - postgres
  postgres:
    image: postgres:13.1
    restart: always
    networks:
      - api_net
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    env_file:
      - .env
    volumes:
    - postgres:/var/lib/postgresql/data
volumes:
  postgres:
networks:
  api_net:
